apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: skywalking-skywalking-helm-oap.skywalking:9411
      envoyAccessLogService:
        address: skywalking-skywalking-helm-oap.skywalking:11800
      envoyMetricsService:
        address: skywalking-skywalking-helm-oap.skywalking:11800
      proxyStatsMatcher:
        inclusionRegexps:
          - .*'
    defaultProviders:
      tracing:
        - "opencensus"
      accessLogging:
        - "envoylogs"
    enablePrometheusMerge: true
    enableEnvoyAccessLogService: true
    enableTracing: true
    extensionProviders:
      - envoyOtelAls:
          port: 4317
          service: "oteld-collector.default.svc.cluster.local"
        name: "envoylogs"
      - name: "otelp"
        opentelemetry:
          service: "oteld-collector.default.svc.cluster.local"
          port: 4317
      - name: "opencensus"
        opencensus:
          service: "oteld-collector.default.svc.cluster.local"
          port: 55678
          context:
            - W3C_TRACE_CONTEXT
