---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skywalking-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: skywalking-event-exporter
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skywalking-event-exporter-cm
data:
  config.yaml: |
    filters:
      - namespace: 
        exporters:
          - skywalking

    exporters:
      skywalking:
        template:
          source:
            service: "{{ .Service.Name }}"
            serviceInstance: "{{ .Pod.Name }}"
            endpoint: ""
          message: "{{ .Event.Message }}"
        address: "skywalking-skywalking-helm-oap.skywalking:11800"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-event-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skywalking-event-exporter
        version: v1
    spec:
      serviceAccountName: skywalking-event-exporter
      containers:
        - name: skywalking-event-exporter
          image:  apache/skywalking-kubernetes-event-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - start
            - -v=debug
            - -c=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: config
      volumes:
        - name: config
          configMap:
            name: skywalking-event-exporter-cm
  selector:
    matchLabels:
      app: skywalking-event-exporter
      version: v1